{% set version = "1.2.0" %}

package:
  name: wsproto
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wsproto/wsproto-{{ version }}.tar.gz
  sha256: ad565f26ecb92588a3e43bc3d96164de84cd9902482b130d0ddbaa9664a85065

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - h11 >=0.9.0,<1.0

test:
  imports:
    - wsproto
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/python-hyper/wsproto/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python, pure state-machine WebSocket implementation.
  description: |
    This repository contains a pure-Python implementation of a WebSocket protocol stack.
    It’s written from the ground up to be embeddable in whatever program you choose to use,
    ensuring that you can communicate via WebSockets, as defined in RFC6455, regardless of your programming paradigm.

    This repository does not provide a parsing layer, a network layer, or any rules about concurrency.
    Instead, it’s a purely in-memory solution, defined in terms of data actions and WebSocket frames.
    RFC6455 and Compression Extensions for WebSocket via RFC7692 are fully supported.
  doc_url: https://wsproto.readthedocs.io/
  dev_url: https://github.com/python-hyper/wsproto

extra:
  recipe-maintainers:
    - maxyme
    - dhirschfeld
    - ocefpaf
