{% set version = "0.15.0" %}

package:
  name: wsproto
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wsproto/wsproto-{{ version }}.tar.gz
  sha256: 614798c30e5dc2b3f65acc03d2d50842b97621487350ce79a80a711229edfa9d

build:
  number: 4
  skip: true  # [py<36]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dataclasses  # [py<37]
    - h11 >=0.8.1

test:
  imports:
    - wsproto

about:
  home: https://github.com/python-hyper/wsproto/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pure Python, pure state-machine WebSocket implementation.'
  description: |
    This repository contains a pure-Python implementation of a WebSocket protocol stack.
    It’s written from the ground up to be embeddable in whatever program you choose to use,
    ensuring that you can communicate via WebSockets, as defined in RFC6455, regardless of your programming paradigm.

    This repository does not provide a parsing layer, a network layer, or any rules about concurrency.
    Instead, it’s a purely in-memory solution, defined in terms of data actions and WebSocket frames.
    RFC6455 and Compression Extensions for WebSocket via RFC7692 are fully supported.
  doc_url: https://wsproto.readthedocs.io/en/latest/
  dev_url: https://github.com/python-hyper/wsproto

extra:
  recipe-maintainers:
    - maxyme
    - dhirschfeld
    - ocefpaf
