travis:
  secure:
    BINSTAR_TOKEN: GrEYkSCifHuh+UImdeRw2d/pZUSgJgBHHam2367fiF937ohEcbkm7PPbWF/fqRUWJ8MWuaoMJT4toOT34Om2Z2oH4v8dSIBKQxOHHsaRGTHXV3lTZ6M+vqtqXAY6+VAfh737urmT3EqWBFyw/Q4PCDdCo13QXfA5O0B2ByQYhqqqWehoIvSb2IILp4E7bH1QsIHnzrCanuXgmQwQDyZs0JYddRBqQ2ho6/UsyJ4LhijaUnMqaLNg7Jnqkf8wTEFa44bGtZYBDIe2VOeohC7UlNH9v8tcSwLJB/oLsPOsqbYU1Gm9uGJOkw+Ve77mesI7eE7Ml2NjH7WIhz+7OB8reoV3wSMOUyeanBk5aN26JAaOoll36Tp6sTxhkIQZ8Y2otsI7kMUM+vaZbp13ZFj5kfIEDqiY7Re/Yrv3Izy/LgmJqrkXipyUA0hsUFWr6u+p5jDBK3POxRA77wLGog1juMiCuFSFAkLq3W9ax+lwT9l8Z/ZrDXd4WlvXoG5J1HQEBvOwn1s4t94U0AOrNWU7yQXB6thO/UI3Uufjvn4geGrHEVpX35aM630yDOziHd0iC4wuLE66hsRqg4SrfPgPdezoyPZDRaIr0YDT5uJqj/JTkvPX1fNRelvPjKVfejXvJihKx8TcAF9YxqM2btHpmJJWarQKWga+Rq3OCUx6G3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
