travis:
  secure:
    BINSTAR_TOKEN: lvXgGLHnFq8dwqM0jGnrG6Y8QHiXMLfsyEjS5yclEMkpmx9Vk6tz77qGR5yh8zb0RqQ+/tHcHsroXq6hb1I4YURCc00vv0m6PPf+wGYkH1kvV6UC5XwnPGV6riQQ73ZLirXqJGeKer3L+dPh6D/pL5xEhRrCjt6QuaiQ3DJKePpZjqmyR37r3rVFgCHEMs0XjXcZ2TK/1bu97oSSfdLJO124qRJtGR8Kf9N51QTqdfOG7r97b2UyOoxs39iGxFt+Xk/wEwbVKk6J4HIZ3vpT4MDV5nHnuOOZ6b0M0HNicKqFaej6NoIWigXdQouApTgosPPr9ky36v/xFT7/PbafnyRYcPO3KYyfNaFkwWoudOROVl3mgdU+A6WOkh6zjqBoIEdy9s4xGsS0DrkdlqyCpP5StghdwAOMO6QLS32GAz50xRaz7+GRQYSVXiRyRSK8i9MxdiCBm6iPlGkPbvVyF0HZB46PGVBtNlUIriafZXPyfe5c+zfDBh+pV1ytpqnvjhaouig7ujYaXNDyksS4+cKOtA0y2ifi4McRMY9RNgnu8wvTBodEB99eeeGJ2haQltw0KdbOpy5wdB09ZbaV6Ry/FUJaJmCWWH9ErZcCibfcUsqSNhqn77WQRjKv8s1OLDbvUzVbrWkkDc25UkCXoaUtAP0ejpoh38qQ3VjpHnw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
